wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.41.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1716830200
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      3:
      - 23
      - 61
      4: 3.10.12
      5: 0.17.0
      6: 4.41.1
      8:
      - 2
      - 5
      13: linux-x86_64
