wandb_version: 1

dataset:
  desc: null
  value: im2smiles-20k
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.1
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718204634
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      3:
      - 2
      - 16
      - 23
      4: 3.10.13
      5: 0.17.1
      6: 4.41.2
      8:
      - 5
      13: linux-x86_64
